/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datn;

/**
 *
 * @author ASUS
 */
public class QLHoSoHocSinh extends javax.swing.JFrame {

    /**
     * Creates new form QLHoSoHocSinh
     */
    public QLHoSoHocSinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jpnel_title = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        hoten = new javax.swing.JLabel();
        hoten1 = new javax.swing.JLabel();
        hoten2 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        hoten3 = new javax.swing.JLabel();
        _3 = new javax.swing.JLabel();
        hoten4 = new javax.swing.JLabel();
        hoten5 = new javax.swing.JLabel();
        hoten6 = new javax.swing.JLabel();
        hoten7 = new javax.swing.JLabel();
        hoten8 = new javax.swing.JLabel();
        hoten9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        txthoten = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        txttimkiem2 = new javax.swing.JTextField();
        _11 = new javax.swing.JLabel();
        txtngaysinh = new javax.swing.JTextField();
        _12 = new javax.swing.JLabel();
        txtnoisinh = new javax.swing.JTextField();
        txtdantoc = new javax.swing.JTextField();
        _13 = new javax.swing.JLabel();
        txttongiao = new javax.swing.JTextField();
        _14 = new javax.swing.JLabel();
        txthotench = new javax.swing.JTextField();
        _15 = new javax.swing.JLabel();
        txtnghenghiepcha = new javax.swing.JTextField();
        _16 = new javax.swing.JLabel();
        txthotenme = new javax.swing.JTextField();
        _17 = new javax.swing.JLabel();
        _18 = new javax.swing.JLabel();
        txtnghenghiepme = new javax.swing.JTextField();
        hoten10 = new javax.swing.JLabel();
        _4 = new javax.swing.JLabel();
        txthoten1 = new javax.swing.JTextField();
        txttimkiem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(50, 27, 140));
        jPanel3.setPreferredSize(new java.awt.Dimension(1024, 30));

        jpnel_title.setBackground(new java.awt.Color(50, 27, 140));
        jpnel_title.setPreferredSize(new java.awt.Dimension(200, 30));

        lbl_title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(204, 204, 204));
        lbl_title.setText("QUẢN LÍ HỒ SƠ HỌC SINH");

        javax.swing.GroupLayout jpnel_titleLayout = new javax.swing.GroupLayout(jpnel_title);
        jpnel_title.setLayout(jpnel_titleLayout);
        jpnel_titleLayout.setHorizontalGroup(
            jpnel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnel_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnel_titleLayout.setVerticalGroup(
            jpnel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnel_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jpnel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1000, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpnel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MÃ HỒ SƠ", "HỌ VÀ TÊN", "GIỚI TÍNH", "NGÀY SINH", "NƠI SINH", "DÂN TỘC", "TÔN GIÁO", "HỌ TÊN CHA", "NGHỀ NGHIỆP CHA", "HỌ TÊN MẸ", "NGHỀ NGHIỆP MẸ"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 1110, 350));

        jPanel5.setBackground(new java.awt.Color(77, 41, 211));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hoten.setFont(new java.awt.Font("Myriad Pro", 0, 11)); // NOI18N
        hoten.setForeground(new java.awt.Color(255, 255, 255));
        hoten.setText("GIỚI TÍNH:");
        jPanel5.add(hoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 90, -1));

        hoten1.setFont(new java.awt.Font("Myriad Pro", 0, 11)); // NOI18N
        hoten1.setForeground(new java.awt.Color(255, 255, 255));
        hoten1.setText("HỌ VÀ TÊN:");
        jPanel5.add(hoten1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 60, -1));

        hoten2.setFont(new java.awt.Font("Myriad Pro", 0, 11)); // NOI18N
        hoten2.setForeground(new java.awt.Color(255, 255, 255));
        hoten2.setText("NGHỆ NGHIỆP MẸ:");
        jPanel5.add(hoten2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 110, -1));

        jRadioButton3.setBackground(new java.awt.Color(77, 41, 211));
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("NỮ");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 50, 20));

        jRadioButton4.setBackground(new java.awt.Color(77, 41, 211));
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("NAM");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 60, 20));

        hoten3.setFont(new java.awt.Font("Myriad Pro", 0, 11)); // NOI18N
        hoten3.setForeground(new java.awt.Color(255, 255, 255));
        hoten3.setText("NGÀY SINH:");
        jPanel5.add(hoten3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 100, -1));

        _3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        _3.setForeground(new java.awt.Color(255, 255, 255));
        _3.setText("__________________________");
        jPanel5.add(_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 110, 10));

        hoten4.setFont(new java.awt.Font("Myriad Pro", 0, 11)); // NOI18N
        hoten4.setForeground(new java.awt.Color(255, 255, 255));
        hoten4.setText("NƠI SINH:");
        jPanel5.add(hoten4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 100, -1));

        hoten5.setFont(new java.awt.Font("Myriad Pro", 0, 11)); // NOI18N
        hoten5.setForeground(new java.awt.Color(255, 255, 255));
        hoten5.setText("DÂN TỘC:");
        jPanel5.add(hoten5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 100, -1));

        hoten6.setFont(new java.awt.Font("Myriad Pro", 0, 11)); // NOI18N
        hoten6.setForeground(new java.awt.Color(255, 255, 255));
        hoten6.setText("TÔN GIÁO:");
        jPanel5.add(hoten6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 100, -1));

        hoten7.setFont(new java.awt.Font("Myriad Pro", 0, 11)); // NOI18N
        hoten7.setForeground(new java.awt.Color(255, 255, 255));
        hoten7.setText("HỌ TÊN CHA:");
        jPanel5.add(hoten7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 100, -1));

        hoten8.setFont(new java.awt.Font("Myriad Pro", 0, 11)); // NOI18N
        hoten8.setForeground(new java.awt.Color(255, 255, 255));
        hoten8.setText("NGHỀ NGHIỆP CHA:");
        jPanel5.add(hoten8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 90, -1));

        hoten9.setFont(new java.awt.Font("Myriad Pro", 0, 11)); // NOI18N
        hoten9.setForeground(new java.awt.Color(255, 255, 255));
        hoten9.setText("HỌ TÊN MẸ");
        jPanel5.add(hoten9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 110, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("QUAY LẠI");
        jButton5.setPreferredSize(new java.awt.Dimension(70, 35));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 89, 30));

        txthoten.setBackground(new java.awt.Color(76, 41, 211));
        txthoten.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        txthoten.setForeground(new java.awt.Color(255, 255, 255));
        txthoten.setBorder(null);
        txthoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthotenActionPerformed(evt);
            }
        });
        jPanel5.add(txthoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 160, 20));

        jTextField24.setEditable(false);
        jTextField24.setBackground(new java.awt.Color(77, 41, 211));
        jTextField24.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        jTextField24.setBorder(null);
        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 210, 20));

        txttimkiem2.setBackground(new java.awt.Color(76, 41, 211));
        txttimkiem2.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        txttimkiem2.setForeground(new java.awt.Color(255, 255, 255));
        txttimkiem2.setText("tìm kiếm");
        txttimkiem2.setBorder(null);
        txttimkiem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimkiem2ActionPerformed(evt);
            }
        });
        jPanel5.add(txttimkiem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 190, 20));

        _11.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        _11.setForeground(new java.awt.Color(255, 255, 255));
        _11.setText("__________________________");
        jPanel5.add(_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 110, 10));

        txtngaysinh.setBackground(new java.awt.Color(76, 41, 211));
        txtngaysinh.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        txtngaysinh.setForeground(new java.awt.Color(255, 255, 255));
        txtngaysinh.setBorder(null);
        txtngaysinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtngaysinhActionPerformed(evt);
            }
        });
        jPanel5.add(txtngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 170, 20));

        _12.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        _12.setForeground(new java.awt.Color(255, 255, 255));
        _12.setText("__________________________");
        jPanel5.add(_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 110, 10));

        txtnoisinh.setBackground(new java.awt.Color(76, 41, 211));
        txtnoisinh.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        txtnoisinh.setForeground(new java.awt.Color(255, 255, 255));
        txtnoisinh.setBorder(null);
        txtnoisinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoisinhActionPerformed(evt);
            }
        });
        jPanel5.add(txtnoisinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 170, 20));

        txtdantoc.setBackground(new java.awt.Color(76, 41, 211));
        txtdantoc.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        txtdantoc.setForeground(new java.awt.Color(255, 255, 255));
        txtdantoc.setBorder(null);
        txtdantoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdantocActionPerformed(evt);
            }
        });
        jPanel5.add(txtdantoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 170, 20));

        _13.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        _13.setForeground(new java.awt.Color(255, 255, 255));
        _13.setText("__________________________");
        jPanel5.add(_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 110, 10));

        txttongiao.setBackground(new java.awt.Color(76, 41, 211));
        txttongiao.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        txttongiao.setForeground(new java.awt.Color(255, 255, 255));
        txttongiao.setBorder(null);
        txttongiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttongiaoActionPerformed(evt);
            }
        });
        jPanel5.add(txttongiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 170, 20));

        _14.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        _14.setForeground(new java.awt.Color(255, 255, 255));
        _14.setText("__________________________");
        jPanel5.add(_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 110, 10));

        txthotench.setBackground(new java.awt.Color(76, 41, 211));
        txthotench.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        txthotench.setForeground(new java.awt.Color(255, 255, 255));
        txthotench.setBorder(null);
        txthotench.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthotenchActionPerformed(evt);
            }
        });
        jPanel5.add(txthotench, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 170, 20));

        _15.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        _15.setForeground(new java.awt.Color(255, 255, 255));
        _15.setText("__________________________");
        jPanel5.add(_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 110, 10));

        txtnghenghiepcha.setBackground(new java.awt.Color(76, 41, 211));
        txtnghenghiepcha.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        txtnghenghiepcha.setForeground(new java.awt.Color(255, 255, 255));
        txtnghenghiepcha.setBorder(null);
        txtnghenghiepcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnghenghiepchaActionPerformed(evt);
            }
        });
        jPanel5.add(txtnghenghiepcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 170, 20));

        _16.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        _16.setForeground(new java.awt.Color(255, 255, 255));
        _16.setText("__________________________");
        jPanel5.add(_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 110, 10));

        txthotenme.setBackground(new java.awt.Color(76, 41, 211));
        txthotenme.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        txthotenme.setForeground(new java.awt.Color(255, 255, 255));
        txthotenme.setBorder(null);
        txthotenme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthotenmeActionPerformed(evt);
            }
        });
        jPanel5.add(txthotenme, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 170, 20));

        _17.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        _17.setForeground(new java.awt.Color(255, 255, 255));
        _17.setText("__________________________");
        jPanel5.add(_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 110, 10));

        _18.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        _18.setForeground(new java.awt.Color(255, 255, 255));
        _18.setText("__________________________");
        jPanel5.add(_18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 110, 10));

        txtnghenghiepme.setBackground(new java.awt.Color(76, 41, 211));
        txtnghenghiepme.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        txtnghenghiepme.setForeground(new java.awt.Color(255, 255, 255));
        txtnghenghiepme.setBorder(null);
        txtnghenghiepme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnghenghiepmeActionPerformed(evt);
            }
        });
        jPanel5.add(txtnghenghiepme, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 170, 20));

        hoten10.setFont(new java.awt.Font("Myriad Pro", 0, 11)); // NOI18N
        hoten10.setForeground(new java.awt.Color(255, 255, 255));
        hoten10.setText("MÃ HỒ SƠ:");
        jPanel5.add(hoten10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 60, -1));

        _4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        _4.setForeground(new java.awt.Color(255, 255, 255));
        _4.setText("__________________________");
        jPanel5.add(_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 110, 10));

        txthoten1.setBackground(new java.awt.Color(76, 41, 211));
        txthoten1.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        txthoten1.setForeground(new java.awt.Color(255, 255, 255));
        txthoten1.setBorder(null);
        txthoten1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthoten1ActionPerformed(evt);
            }
        });
        jPanel5.add(txthoten1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 170, 20));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 510));

        txttimkiem.setBackground(new java.awt.Color(76, 41, 211));
        txttimkiem.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        txttimkiem.setForeground(new java.awt.Color(255, 255, 255));
        txttimkiem.setText("tìm kiếm");
        txttimkiem.setBorder(null);
        txttimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimkiemActionPerformed(evt);
            }
        });
        getContentPane().add(txttimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 140, 20));

        jButton1.setText("Tìm Kiếm");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ngangtim.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 700, 80));

        jPanel9.setBackground(new java.awt.Color(77, 41, 211));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("XÓA");
        jButton4.setPreferredSize(new java.awt.Dimension(70, 35));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("THÊM");
        jButton2.setPreferredSize(new java.awt.Dimension(70, 35));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("SỮA");
        jButton3.setPreferredSize(new java.awt.Dimension(70, 35));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("MỚI");
        jButton6.setPreferredSize(new java.awt.Dimension(70, 35));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 800, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimkiemActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void txthotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthotenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthotenActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void txttimkiem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimkiem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimkiem2ActionPerformed

    private void txtngaysinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtngaysinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtngaysinhActionPerformed

    private void txtnoisinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoisinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoisinhActionPerformed

    private void txtdantocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdantocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdantocActionPerformed

    private void txttongiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttongiaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttongiaoActionPerformed

    private void txthotenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthotenchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthotenchActionPerformed

    private void txtnghenghiepchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnghenghiepchaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnghenghiepchaActionPerformed

    private void txthotenmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthotenmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthotenmeActionPerformed

    private void txtnghenghiepmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnghenghiepmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnghenghiepmeActionPerformed

    private void txthoten1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthoten1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthoten1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLHoSoHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLHoSoHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLHoSoHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLHoSoHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLHoSoHocSinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _11;
    private javax.swing.JLabel _12;
    private javax.swing.JLabel _13;
    private javax.swing.JLabel _14;
    private javax.swing.JLabel _15;
    private javax.swing.JLabel _16;
    private javax.swing.JLabel _17;
    private javax.swing.JLabel _18;
    private javax.swing.JLabel _3;
    private javax.swing.JLabel _4;
    private javax.swing.JLabel hoten;
    private javax.swing.JLabel hoten1;
    private javax.swing.JLabel hoten10;
    private javax.swing.JLabel hoten2;
    private javax.swing.JLabel hoten3;
    private javax.swing.JLabel hoten4;
    private javax.swing.JLabel hoten5;
    private javax.swing.JLabel hoten6;
    private javax.swing.JLabel hoten7;
    private javax.swing.JLabel hoten8;
    private javax.swing.JLabel hoten9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JPanel jpnel_title;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txtdantoc;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txthoten1;
    private javax.swing.JTextField txthotench;
    private javax.swing.JTextField txthotenme;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txtnghenghiepcha;
    private javax.swing.JTextField txtnghenghiepme;
    private javax.swing.JTextField txtnoisinh;
    private javax.swing.JTextField txttimkiem;
    private javax.swing.JTextField txttimkiem2;
    private javax.swing.JTextField txttongiao;
    // End of variables declaration//GEN-END:variables
}
